language: php

php: 7.1

env:
  - LARAVEL_VERSION=5.2.*
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.*

matrix:
  include:
    - php: 5.5
      env: LARAVEL_VERSION=5.2.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require "laravel/framework:${LARAVEL_VERSION}" --no-update; fi;
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
